<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Api.CommonProtos" Version="2.17.0" />
    <PackageReference Include="Google.Api.Gax" Version="4.14.0" />
    <PackageReference Include="Google.Api.Gax.Grpc" Version="4.14.0" />
    <PackageReference Include="Google.Api.Gax.Grpc.GrpcCore" Version="3.7.0" />
    <PackageReference Include="Google.Apis" Version="1.75.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Google.Apis.Core" Version="1.75.0" />
    <PackageReference Include="Google.Cloud.Vision.V1" Version="3.8.0" />
    <PackageReference Include="Google.LongRunning" Version="3.5.0" />
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Auth" Version="2.80.0" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="Grpc.Core.Api" Version="2.80.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Buffers" Version="4.6.1" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>
</Project>
